name = "SmartMonitoringSchemes"
repo = "git@github.com:SmartMonitoringSchemes/Registry.git"
uuid = "bab96e84-c8f8-4ca3-85f9-6ca5c8f91499"
description = ""

[packages.d69f1d75-0f53-4bd4-8114-76337d5140b8]
name = "HDPHMM"
path = "packages/HDPHMM"

[packages.c2d32e4c-7064-491d-a5e3-8549892f5912]
name = "ThesisTools"
path = "packages/ThesisTools"
