name = "SmartMonitoringSchemes"
repo = "git@github.com:SmartMonitoringSchemes/Registry.git"
uuid = "bab96e84-c8f8-4ca3-85f9-6ca5c8f91499"
description = ""

[packages.9aa3e4a5-e084-4c6a-9aeb-c6df264de966]
name = "ParsimoniousMonitoring"
path = "packages/ParsimoniousMonitoring"
